add_newline = false

[line_break]
disabled = true

[character]
error_symbol = "[âœ–](bold red)"

[git_status]
ignore_submodules = true

# https://starship.rs/presets/no-nerd-font#no-nerd-fonts-preset
[nodejs]
symbol = "[â¬¢](bold green) "

[battery]
full_symbol = "ğŸ”‹  "
charging_symbol = "ğŸ”Œ "
discharging_symbol = "ğŸª«  "
unknown_symbol = "â“ "
empty_symbol = "â— "
